// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn3qZP7ccJDP75PvLN7hlvsMVC_6ut1GY',
    appId: '1:939792290969:web:573e59937dd41a49ec1408',
    messagingSenderId: '939792290969',
    projectId: 'fun-98543',
    authDomain: 'fun-98543.firebaseapp.com',
    storageBucket: 'fun-98543.appspot.com',
    measurementId: 'G-M7WP0ZED9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJSHIjLffPA48Kr06GWKgYAyJbnYSUE0',
    appId: '1:939792290969:android:8ffb6343d8898a92ec1408',
    messagingSenderId: '939792290969',
    projectId: 'fun-98543',
    storageBucket: 'fun-98543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkDVjdpOecXrxceWKt0PBbh420ZfG9uUo',
    appId: '1:939792290969:ios:ead335cb4c4fcbb1ec1408',
    messagingSenderId: '939792290969',
    projectId: 'fun-98543',
    storageBucket: 'fun-98543.appspot.com',
    iosClientId: '939792290969-87icq9669dd79rc1jmp4i568rhlq001k.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskitNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkDVjdpOecXrxceWKt0PBbh420ZfG9uUo',
    appId: '1:939792290969:ios:76751a2d709a0e1bec1408',
    messagingSenderId: '939792290969',
    projectId: 'fun-98543',
    storageBucket: 'fun-98543.appspot.com',
    iosClientId: '939792290969-ss5u0ouhtlah71oju7pmk0fd7m3uqkoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskitNew.RunnerTests',
  );
}
